local Main = {}

Main.RENDER_WIDTH = 640
Main.RENDER_HEIGHT = 360
Main.DEFAULT_FILTER = "nearest"

Main.CHARACTER_SIZE = 32

Main.TILE_SCALE = 1
Main.TILE_SIZE = 32
Main.WALL_TILE_SIZE = 16
Main.MIN_WIDTH_TILEMAP = 15
Main.MAX_WIDTH_TILEMAP = 20
Main.MIN_HEIGHT_TILEMAP = 10
Main.MAX_HEIGHT_TILEMAP = 15
Main.WALL_SHADOW_OFFSET = 5

Main.ASSETS_PATH = "stuff/assets/"
Main.TILE_PATH = "stuff/assets/tiles/"
Main.DEBUG = false

Main.SHADING = true

Main.MIN_ENEMY_SOUL = 5
Main.MAX_ENEMY_SOUL = 20

Main.BACKGROUND_COLOR = {0, 0, 0}
Main.SHADOW_COLOR = {0, 0, 0, 0.5}

return Main